"$schema" = "https://raw.githubusercontent.com/JanDeDobbeleer/oh-my-posh/main/themes/schema.json"
version = 4
final_space = true

[[blocks]]
type = "prompt"
alignment = "left"

	[[blocks.segments]]
	type = "executiontime"
	style = "plain"
	template = """
	     {{$str := printf " 󱦟 Duration: %s" .FormattedMs}}\
	     {{$len := len $str}}\
	     ┌{{ printf "%*s" $len "" | replace " " "─"}}┐
	     │ {{$str}}  │
	     └{{ printf "%*s" $len "" | replace " " "─"}}┘\
	    """
	foreground = "p:violet_bright"

		[blocks.segments.options]
		style = "roundrock"


# Line 1
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

	[[blocks.segments]]
	type = "text"
	style = "plain"
	powerline_symbol = ""
	template = "\n╭──"
	foreground = "p:snow_dark"

	[[blocks.segments]]
	type = "session"
	style = "diamond"
	powerline_symbol = ""
	template = "{{ .UserName }}@{{ .HostName }}"
	foreground = "p:snow_bright"
	background = "p:snow_dark"
	leading_diamond = ""
	trailing_diamond = ""

	[[blocks.segments]]
	type = "text"
	style = "plain"
	foreground = "p:snow_dark"
	template = "─"

	[[blocks.segments]]
	type = "path"
	style = "diamond"
	template = " {{ if not .Writable }}󰉐 {{ else }} {{ end }} {{ .Path }} "

	foreground = "p:yellow_bright"
	foreground_templates = [
		"{{ if not .Writable }}p:red_bright{{ end }}"
	]
	background = "p:snow_dark"
	leading_diamond = ""
	trailing_diamond = ""

		[blocks.segments.options]
		style = "mixed"
		mixed_threshold = 5

[[blocks]]
type = "prompt"
alignment = "right"
filler = "<p:snow_dark>─"

	[[blocks.segments]]
	type = "time"
	style = "diamond"
	background = "p:snow_dark"
	foreground = "p:orange_bright"
	template = " {{ .CurrentDate | date \"Mon 02 Jan 15:04\" }} "
	leading_diamond = ""
	trailing_diamond = ""

	[[blocks.segments]]
	type = "text"
	style = "plain"
	foreground = "p:snow_dark"
	template = "──╮"


# Line 2
[[blocks]]
type = "prompt"
alignment = "left"
newline = true
filler = "<p:snow_dark>│</>"

	[[blocks.segments]]
	type = "git"
	style = "plain"

	template = """
	<p:snow_dark>│</>  Repository Git: <p:orange_bright>\
	  {{ if .UpstreamURL}}{{url .RepoName .UpstreamURL}}{{ else }}{{ .RepoName }}{{end}}</>  \
	  Branch: <p:purple_bright>{{ .HEAD }}</>\
	"""

	foreground = "#d3c6aa"

		[blocks.segments.options]
		fetch_status = true

	    [blocks.segments.cache]
	    duration = "2s"
	    strategy = "session"


[[blocks]]
type = "prompt"
alignment = "right"
filler = " "

	[[blocks.segments]]
	type = "git"
	style = "plain"
	foreground = "p:snow_dark"
	template = "│"


# Line 3
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

	[[blocks.segments]]
	type = "git"
	style = "plain"

	template = """
	<p:snow_dark>│</>  {{ if .UpstreamURL}}Upstream: <p:orange_bright> {{ .Ahead }}</>/<p:blue_bright>{{ .Behind }}</>  {{end}}\
	  Changed: <p:green_bright>+{{ .Working.Added }}</>/<p:yellow_bright>{{ .Working.Modified }}</>/<p:red_bright>-{{ .Working.Deleted }}</>  \
	  Staged: <p:green_bright>+{{ .Staging.Added }}</>/<p:yellow_bright>{{ .Staging.Modified }}</>/<p:red_bright>-{{ .Staging.Deleted }}</>\
	"""

	foreground = "#d3c6aa"

		[blocks.segments.options]
		fetch_status = true

	    [blocks.segments.cache]
	    duration = "2s"
	    strategy = "session"


[[blocks]]
type = "prompt"
alignment = "right"
filler = " "

	[[blocks.segments]]
	type = "git"
	style = "plain"
	foreground = "p:snow_dark"
	template = "│"


# Line 4
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

	[[blocks.segments]]
	type = "text"
	style = "plain"
	foreground = "#d3c6aa"

	template = "{{ if .Env.NIX_CURRENT_FLAKE_CONFIG }}<p:snow_dark>│</>  Nix Flake: <p:snow_bright> {{ .Env.NIX_CURRENT_FLAKE_CONFIG }}  </>{{ end }}"

		[blocks.segments.options]
		var_name = "NIX_CURRENT_FLAKE_CONFIG"

	[[blocks.segments]]
	type = "nix-shell"
	style = "plain"
	foreground = "#d3c6aa"

	template = "{{ if not .Env.NIX_CURRENT_FLAKE_CONFIG }}<p:snow_dark>│</>  {{ end }}Nix Shell: <p:snow_bright> {{ if .Env.name }}{{ .Env.name }}:{{end}}</><p:red_bright>{{ .Type }}  </>"


[[blocks]]
type = "prompt"
alignment = "right"
filler = " "

	[[blocks.segments]]
	type = "text"
	style = "plain"
	foreground = "p:snow_dark"
	template = "{{ if or .Env.NIX_CURRENT_FLAKE_CONFIG .Env.IN_NIX_SHELL .Env.name .Env.NIX_SHELL_PACKAGES }}│{{ end }}"


# Line 5
[[blocks]]
type = "prompt"
alignment = "left"
newline = true

	[[blocks.segments]]
	type = "python"
	style = "plain"
	foreground = "#d3c6aa"

	template = "<p:snow_dark>│</>  {{ if .Venv }}Python env: <p:violet_bright>󱧼 {{ .Venv }}  </>{{end}}Python version: <p:green_bright> {{ .Full }}  </>"

		[blocks.segments.options]
	    fetch_virtual_env = true
		display_mode = "context"
		tooling = ['uv', 'python3', 'python']

	    [blocks.segments.cache]
	    duration = "1m"
	    strategy = "folder"

	[[blocks.segments]]
	type = "node"
	style = "plain"
	foreground = "#d3c6aa"

	template = "Node version: <p:orange_bright>{{ .Full }}{{if .PackageManagerIcon }} on {{ .PackageManagerIcon }} {{ .PackageManagerName }}{{end}}  </>"

		[blocks.segments.options]
		display_mode = "context"
		fetch_package_manager = true

		[blocks.segments.cache]
	    duration = "1m"
	    strategy = "folder"

	[[blocks.segments]]
	type = "php"
	style = "plain"
	foreground = "#d3c6aa"

	template = "PHP version: <p:blue_bright>  {{if .Full}}{{ .Full }}{{else}}<p:red_bright>Not found</>{{end}}</>  "

		[blocks.segments.options]
		display_mode = "context"

		[blocks.segments.cache]
	    duration = "1m"
	    strategy = "folder"


[[blocks]]
type = "prompt"
alignment = "right"
filler = " "

	[[blocks]]
	type = "prompt"
	alignment = "right"
	filler = " "

		[[blocks.segments]]
		type = "text"
		style = "plain"
		foreground = "p:snow_dark"
		template = """\
			{{ if or .Env.VIRTUAL_ENV .Env.NODE_VERSION .Env.PHP_VERSION \
			(glob "*.py") (glob ".venv") (glob "pyproject.toml") \
			(glob "package.json") (glob "composer.json") (glob "*.php") \
			}}│{{ end }}\
		"""


[palette]
# H: 19
orange_bright = "#fa986a"
orange_dark = "#5e493f"

# H: 40
yellow_dark = "#5f4b25"
yellow_bright = "#faca6a"

# H: 134
green_dark = "#374C3C"
green_bright = "#83C091"

# H: 201
snow_dark = "#304c5b"
snow_bright = "#d0e2eb"

# H: 223
blue_dark = "#2f3b5a"
blue_bright = "#6f8cd3"

# H: 271
violet_dark = "#43255f"
violet_bright = "#ae7fdb"

# H: 325
pink_dark = "#5e3f51"
pink_bright = "#f58bc9"

# H: 359
red_dark = "#4c3737"
red_bright = "#fa6a6d"