# Starship prompt setup
"$schema" = 'https://starship.rs/config-schema.json'

# Config
add_newline = true

format = """
$cmd_duration
[╭──[$username](bg:snow_dark)[$hostname](bg:snow_dark fg:snow_bright)─$directory─$fill$time──╮](fg:snow_dark)
[│](fg:snow_dark)$blank_fill[│](fg:snow_dark)
[╰─](fg:snow_dark) $character
"""

right_format = """
[─](fg:snow_dark)$battery[](fg:snow_dark)$shell$os[──┘](fg:snow_dark)
"""

palette = "everforest"

[palettes.everforest]
# H: 19
orange_bright = "#fa986a"

# H: 40
yellow_dark   = "#5f4b25"
yellow_bright = "#faca6a"

# H: 134
green_dark   = "#374C3C"
green_bright = "#83C091"

# H: 179
snow_dark   = "#374c4c"
snow_bright = "#83c0bf"

# H: 271
violet_dark   = "#43255f"
violet_bright = "#ae7fdb"

# H: 359
red_dark   = "#4c3737"
red_bright = "#fa6a6d"

[cmd_duration]
show_notifications = true

format = """
    [┌───────────────────────────────┐](fg:violet_bright)
    [  󱦟 Duration: $duration          ](fg:violet_bright)
    [└───────────────────────────────┘](fg:violet_bright)
"""

[username]
format = "[$user]($style)"
style_root = 'fg:red_bright bg:snow_dark'
style_user = 'fg:snow_bright bg:snow_dark'

[hostname]
format = "@$hostname"

[fill]
symbol = "─"
style  = "fg:snow_dark"

[character]
success_symbol = "[](fg:snow_bright)"
error_symbol   = "[](fg:red_bright)"

[directory]
format = "[[$read_only$path]($style)]($read_only_style)"
style  = "fg:yellow_bright bg:snow_dark"

read_only       = "󱪨 "
read_only_style = "fg:red_bright bg:snow_dark"

[time]
disabled    = false
format      = "[$time]($style)"
style       = "fg:orange_bright bg:snow_dark"
time_format = "%a %d %b %R"

[battery]
format = "[](fg:snow_dark)[$symbol$percentage]($style)[─](fg:snow_dark)"

[[battery.display]]
threshold = 20
style     = "fg:orange_bright bg:snow_dark"

[shell]
disabled = false
format   = "[$indicator ]($style)"
style    = "fg:snow_bright bg:snow_dark"

[os]
disabled = false
format   = "[on $symbol$name $version]($style)"
style    = "fg:snow_bright bg:snow_dark"

[os.symbols]
AlmaLinux = " "
Android = " "
CachyOS = " "
Fedora = " "
NixOS = " "
RockyLinux = " "
Ubuntu = " "
Windows = " "